# Stage 1: Build
FROM golang:1.23.0-alpine AS build

WORKDIR /src

COPY . .

WORKDIR /src/cmd/consumer

RUN go mod download
RUN go build -o /bin/consumer

# Stage 2: Create the final image
FROM alpine:latest

# Устанавливаем CA сертификаты для поддержки SSL/TLS, если необходимо
RUN apk add --no-cache ca-certificates

COPY --from=build /bin/consumer /bin/consumer

CMD ["/bin/consumer"]
